services:
  postgres:
    # PG_VERSION=18.1
    image: postgres:18.1
    restart: always
    networks:
      - backend
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  adminer:
    # ADMINER_VERSION=5.4.1
    image: adminer:5.4.1
    restart: always
    networks:
      - backend
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=pepa-linha-dark

networks:
  backend:
